### ISSUE TITLE
New flag: sudo canasta --version

### ISSUE THREAD

**Issue by lexsulzer** [CanastaWiki/Canasta-Go#17]
Would `sudo canasta --version` be useful/appreciated by users?

**Comment by yaronkoren** [comment]
I think so!

**Comment by yaronkoren** [comment]
@lexsulzer - actually, having talked it over with some people, I'm not sure how useful this would be. If users want to see the actual version of Canasta being used, they can already call "sudo canasta list" - which shows the version for each Canasta instance, since they might be different. Or is the idea just to show the version of the Canasta CLI? If so, the CLI currently has no versioning - and I'm not sure how useful this would be anyway, since hopefully the CLI will not see any breaking changes.

Thoughts?

**Comment by lexsulzer** [comment]
I wanted to check whether the binary I last downloaded by https://github.com/CanastaWiki/Canasta-CLI/blob/main/install.sh was actually the latest as per https://github.com/CanastaWiki/Canasta-CLI/releases or whether I needed to repeat install.sh.

**Comment by yaronkoren** [comment]
Oh, okay - you did actually want to see the version of the CLI. Well, this "--version" flag makes sense, then - although the first step is to actually have CLI versions. :)
