### ISSUE TITLE
`docker-compose` might not be in `$PATH` even though it is correctly installed.

### ISSUE THREAD

**Issue by hexmode** [CanastaWiki/Canasta-Go#21]
I was setting up docker-compose for my podman installation and this led me to read over the documentation for its installation and saw that the "[install the plugin manually](https://docs.docker.com/compose/install/linux/#install-the-plugin-manually)" method that I had to use in my RHEL machine (so that I didn't accidentally pull in docker since I'm using podman), it recommends installing `docker-compose` under `~/.docker/cli-plugins` or `/usr/local/lib/docker/cli-plugins` if you want it installed site-wide.

When docker-compose is installed in this location, the docker command will invoke it if you call `docker compose` as the documentation suggests.

Even though docker can find docker-compose in this way, the canasta cli will not find it because it is not in the path.

Additionally, if `docker-compose` is installed in `/usr/local/bin`, most invocations of sudo will not find it since `/usr/local/bin` is not in sudo's `$PATH` (at least, in the default install).

Incidentally, podman doesn't support the `~/.docker/cli-plugins` or `/usr/local/lib/docker/cli-plugins` convention.

Given the variety of locations that docker-compose can end up in when someone is following the installation instructions from docker-compose itself, it seems there should be a way to specify the full path to the command when the `docker-compose` orchestrator is used.

**Comment by amalpaul54111** [comment]
Yeah, we could have a command to set the docker-path inside the `/etc/canasta/conf.json` and retrieved by the functions calling docker-compose.

**Comment by freephile** [comment]
@hexmode With the new check in install.sh being `if ! docker compose version >/dev/null 2>&1; then` can you comment on whether that check fails in the scenarios you describe? I want to close this bug as resolved.

The latest [Canasta CLI documentation](https://canasta.wiki/cli/) says to install Docker Desktop for Windows and Mac, while you should use the Docker **repos** for Linux installs. I believe the official Docker repos will work in your RHEL use case. 

As an aside, you can run Podman and Docker engine on the same host since they are both OCI compliant. I'm running at least Podman Desktop on my Windows machine alongside (Docker Engine and) Docker Desktop.

**Comment by yaronkoren** [comment]
I believe this can be closed, especially since it refers specifically to docker-compose (with a hyphen), which is now no longer supported. If there's still any issue with checking for the presence of Docker Compose, there should be a new issue created for it.
