### ISSUE TITLE
Need some sort of progress information during initial create

### ISSUE THREAD

**Issue by hexmode** [CanastaWiki/Canasta-Go#25]
It just seems to sit there:

``` shellsession
$ canasta create -a WikiSysop -r -w Wiki -n wiki.wiki -i wiki
Setting up Canasta

```

**Comment by yaronkoren** [comment]
I agree that it would be great to have a progress display, with one line getting filled by asterisks or something - I think either yum or apt (or both) do it that way.

**Comment by aerowisca** [comment]
Hello, I've worked on this issue and created a PR for the same. Can one of the maintainers please assign me the issue? Thanks.

**Comment by hexmode** [comment]
@yaronkoren I don't have permission to assign @aerowisca.  Could you?

**Comment by yaronkoren** [comment]
I can assign this (well, anyone could, really - it's just a matter of saying "you are assigned"), but I want to clarify this first.

@aerowisca - first of all, nice job! The patch looks good, and the animated GIFs you added make it very easy to see what it does. (Though the fact that neither command actually worked looks like a major problem, unrelated to your code.)

However, I don't know if you saw, but there is already a patch to create a progress bar, #54. It is not completed, and its developer (@gitmapd) is no longer actively working on it, but it might be the better approach, because it shows a "progress bar" that gets filled in, so users, at least in theory, have a sense for how much longer it will take. Did you see this other PR? Do you have any thoughts about it?

@hexmode - if you have any thoughts on the two approaches, that would be welcome as well.

**Comment by hexmode** [comment]
@yaronkoren initial impressions:
- something that works is better than something that does not
- progress bars can be deceptive since they give you the idea that, say, 50% of the time has past when that may not be the case
- a spinner like the one implemented here looks identical to the one that comes with the glab ort gh cli (I don't remember which atm).

**Comment by yaronkoren** [comment]
These are all valid points - and by "glab ort gh cli" I assume you mean "GitLab or GitHub CLI". I'm guessing it's GitLab, by the way, because I don't remember GitHub having spinners.

To the first point, obviously something that works is better, but my thought was that maybe @aerowisca could switch to using that other patch as the basis for a new patch. On the other hand, as you note, a truly accurate progress bar may be difficult or impossible to accomplish - that's actually one of the main issues with the current progress bar patch.

Anyway, enough delaying: @aerowisca, you are hereby assigned this issue!

I'm curious if anyone else has thoughts on a progress bar vs. spinner-plus-time-indicator, though. @bawolff, @gitmapd, @jeffw16 - any opinion?

**Comment by aerowisca** [comment]
@yaronkoren  Yes, of course, I went through the PR (along with the approach and discussion there). I'm aware that I shouldn't be doing overlapping work without informing the maintainers. I saw that the PR didn't work as expected, and the progress was misleading. So, instead of waiting for someone to assign me the issue, I directly started working on it, as the original contributor was inactive and no one was working on it.

 About the commands not working to completion, I hope you'll excuse me. That's totally on me. I was trying to do some experiments, in order to trigger the failure paths as well (such as stopping installation midway, manually deleting a subset of docker containers, tampering with the config etc).

About the technical details : IMHO, it's not a great idea to show progress bar, since we ourselves don't know how much time it'd take to complete. The previous PR just split the time into slots of 15 each, but of course, as mentioned by @bawolff the user might expect the first 25% to be the same duration as the last 25%, which can be misleading due to `docker-compose up -d` runtime.

**Comment by yaronkoren** [comment]
@aerowisca - it's great to hear that you've thought about this issue. Yes, asking about it first would have been better, but it's also nice that you were excited to get started on development. And it's a relief to hear that the CLI is not completely failing every time!

**Comment by yaronkoren** [comment]
Done in #101 (which itself is just a rebased version of #74, so the main credit goes to @aerowisca).
