### ISSUE TITLE
Add option to choose version to install

### ISSUE THREAD

**Issue by jeffw16** [CanastaWiki/Canasta-Go#34]
Users should be able to choose what version they want to install, as well as any derivative images.

For instance, I might not want Canasta 1.2.0 if it is the most recently released version. Instead, I could want Canasta 1.1.2 for backwards compatibility reasons. Or, I might want to use the hardened version of Canasta or even Open CSP on Canasta. None of this is possible at the moment.

**Comment by heyimNaveen** [comment]
I'm interested in contributing to this project GSOC2023 and  I would like to work on issue #34. Can someone assign it to me, or can you tell me anyone working on this issue.

**Comment by jeffw16** [comment]
@heyimNaveen this is now assigned to you. Please start over and do not use any of the code from #35.

**Comment by chl178** [comment]
I noticed that there hasn't been any progress on this issue for two weeks, and I believe that this isn't a very difficult issue. Moreover, some others have already completed the work before. 
So please forgive me, @jeffw16 , I know you are very very busy lately, so I didn't bother you, let you reassign it to me, but I couldn't help but resolve this issue because this can prove my programming ability other than go.
I hope you don't mind my enthusiasm for contributing while following the "two weeks" rules.

**Comment by jeffw16** [comment]
@chl178 sure, this is assigned to you now
